version: '2'

services:
  freeswitch:
    build: .
    container_name: fusionpbx_freeswitch
    volumes:
      # - ./httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs/freeswitch:/var/log/freeswitch
      # - ./logs/supervisor:/var/log/supervisor
      # - ./html:/var/www/html
    networks:
      default:
        ipv4_address: 172.29.0.5
    restart: always
    ports:
    - "5160-5161:5160-5161/udp"
    - "5060-5060:5060-5060/udp"
    - "8082:8082/tcp"
    - "10000-10050:10000-10050/udp"
    # volumes:
      # - freepbx-apache:/etc/apache2
      # - freepbx-asterisk-config:/etc/asterisk
      # - freepbx-mysql:/var/lib/mysql
      # - freepbx-asterisk-spool:/var/spool/asterisk
      # - freepbx-asterisk-data:/var/lib/asterisk

# volumes:
#   freepbx-apache:
#   freepbx-asterisk-config:
#   freepbx-mysql:
#   freepbx-asterisk-spool:
#   freepbx-asterisk-data:

# networks:
#   default:
#     external:
#       name: voice_ip_default

networks:
  default:
    ipam:
      config:
        - subnet: 172.29.0.0/16
