version: '2'

services:
  asterisk:
    build: ./asterisk
    container_name: freepbx
    volumes:
      # - ./conf/:/etc/asterisk/conf/
      - ./asterisk/supervisor:/etc/supervisor
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./logs/httpd:/etc/httpd/logs
      - ./logs/asterisk:/var/log/asterisk
      # - ./logs/supervisor:/var/log/supervisor
      - ./html:/var/www/html
      
    networks:
      default:
        ipv4_address: 172.29.0.3
    restart: always
    ports:
    - "5160-5161:5160-5161/udp"
    - "5060-5060:5060-5060/udp"
    - "8082:8082/tcp"
    - "10000-10050:10000-10050/udp"
    # volumes:
      # - freepbx-apache:/etc/apache2
      # - freepbx-asterisk-config:/etc/asterisk
      # - freepbx-mysql:/var/lib/mysql
      # - freepbx-asterisk-spool:/var/spool/asterisk
      # - freepbx-asterisk-data:/var/lib/asterisk

# volumes:
#   freepbx-apache:
#   freepbx-asterisk-config:
#   freepbx-mysql:
#   freepbx-asterisk-spool:
#   freepbx-asterisk-data:

networks:
  default:
    ipam:
      config:
        - subnet: 172.29.0.0/16
